- websocket-ballerina/Package.md
> Fix Package.md heading

- .github/workflows/build-master.yml
- .github/workflows/stdlib-workflow-trigger.yml
> Rename the master branch to main in Github actions

- websocket-native/build.gradle
> Remove unnecessary native code publish

- websocket-ballerina/tests/websocket_authentication_success_server.bal
- websocket-ballerina/tests/websocket_client_close.bal
- websocket-ballerina/tests/websocket_client_exceptions.bal
- websocket-ballerina/tests/websocket_cookie_server.bal
- websocket-ballerina/tests/websocket_error_log_service.bal
- websocket-ballerina/tests/websocket_simple_proxy_server.bal
- websocket-ballerina/tests/websocket_ssl_proxy.bal
> Update to new log API changes

- gradle.properties
- websocket-native/src/main/java/org/ballerinalang/net/websocket/WebSocketConstants.java
> Update websocket version

- websocket-ballerina/tests/websocket_client_exceptions.bal
- websocket-ballerina/websocket_connector.bal
- websocket-native/src/main/java/org/ballerinalang/net/websocket/WebSocketResourceDispatcher.java
- websocket-native/src/main/java/org/ballerinalang/net/websocket/WebSocketService.java
- websocket-native/src/main/java/org/ballerinalang/net/websocket/WebSocketUtil.java
- websocket-native/src/main/java/org/ballerinalang/net/websocket/server/WebSocketServerService.java
- websocket-native/src/main/java/org/ballerinalang/net/websocket/serviceendpoint/Detach.java
- websocket-native/src/main/java/org/ballerinalang/net/websocket/serviceendpoint/Register.java
> Fix breaking language API changes

- websocket-ballerina/build.gradle
- websocket-ballerina/tests/sync_client_test_bytes.bal
- websocket-ballerina/tests/sync_client_test_text.bal
> Add tests to the ballerina build task and remove unwanted casting in Ballerina code

- build.gradle
- gradle.properties
- websocket-ballerina/build.gradle
> Remove Stringutils dependency and add regex transitive dependency

- websocket-ballerina/build.gradle
- websocket-ballerina/tests/03_push_and_onText.bal
- websocket-ballerina/tests/29_ssl_echo.bal
- websocket-ballerina/tests/corrupted_frame_client_test.bal
- websocket-ballerina/tests/corrupted_frame_server_test.bal
- websocket-ballerina/tests/sync_client_test_bytes.bal
- websocket-ballerina/tests/sync_client_test_text.bal
- websocket-ballerina/tests/websocket_client_close.bal
- websocket-ballerina/tests/websocket_client_exceptions.bal
- websocket-ballerina/tests/websocket_client_service.bal
- websocket-ballerina/tests/websocket_custom_headers_test.bal
- websocket-ballerina/tests/websocket_error_log_service.bal
- websocket-ballerina/tests/websocket_missing_resources.bal
- websocket-ballerina/tests/websocket_ping_pong.bal
- websocket-ballerina/tests/websocket_pushText_failure.bal
- websocket-ballerina/tests/websocket_simple_proxy_server.bal
- websocket-ballerina/tests/websocket_simple_server_without_ping_resource.bal
- websocket-ballerina/tests/websocket_ssl_proxy.bal
> Remove unnecessary checks in listener creation

- websocket-ballerina/build.gradle
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
> Update ballerina command to bal command

- websocket-ballerina/service_endpoint.bal
This is to align with HTTP's https://github.com/ballerina-platform/module-ballerina-http/pull/171
> Add request limit configs to listener

- websocket-ballerina/tests/websocket_client_service.bal
- websocket-ballerina/websocket_client.bal
- websocket-ballerina/websocket_errors.bal
- websocket-ballerina/websocket_sync_client.bal
- websocket-native/src/main/java/org/ballerinalang/net/websocket/client/InitEndpoint.java
- websocket-native/src/main/java/org/ballerinalang/net/websocket/client/RetryInitEndpoint.java
> Make client return errors from native code

- websocket-ballerina/Package.md
- websocket-ballerina/tests/corrupted_frame_client_test.bal
- websocket-ballerina/tests/sync_client_test_bytes.bal
- websocket-ballerina/tests/sync_client_test_text.bal
- websocket-ballerina/tests/websocket_client_exceptions.bal
- websocket-ballerina/tests/websocket_client_failure.bal
- websocket-ballerina/tests/websocket_client_service.bal
- websocket-ballerina/tests/websocket_custom_headers_test.bal
- websocket-ballerina/tests/websocket_ping_pong.bal
- websocket-ballerina/tests/websocket_pushText_failure.bal
- websocket-ballerina/websocket_client.bal
- websocket-ballerina/websocket_sync_client.bal
- websocket-native/src/main/java/org/ballerinalang/net/websocket/WebSocketConstants.java
Add dynamic listener to the websocket client
Rename SyncClient to Client
Remove sync client related docs
> Add dynamic listener to the websocket client

- build.gradle
- gradle.properties
- websocket-ballerina/build.gradle
> Remove config module from build

- websocket-ballerina/service_endpoint.bal
- websocket-ballerina/websocket_client.bal
- websocket-ballerina/websocket_connector.bal
- websocket-ballerina/websocket_failover_client.bal
- websocket-ballerina/websocket_sync_client.bal
Related Issue: ballerina-platform/ballerina-lang#28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
> Change the name of the `java` langlib module to `jballerina.java`

- websocket-native/build.gradle
- websocket-native/spotbugs-exclude.xml
- websocket-native/src/main/java/org/ballerinalang/net/websocket/WebSocketResourceDispatcher.java
- websocket-native/src/main/java/org/ballerinalang/net/websocket/actions/websocketconnector/WebSocketConnector.java
- websocket-native/src/main/java/org/ballerinalang/net/websocket/server/OnUpgradeResourceCallback.java
- websocket-native/src/main/java/org/ballerinalang/net/websocket/server/WebSocketServerService.java
> Enable spot bugs

- .github/workflows/build-master.yml
- .github/workflows/pull-request.yml
- websocket-ballerina/build.gradle
> Add test coverage reports

- websocket-ballerina/build.gradle
> Avoid running tests twice when publishing

- websocket-native/src/main/java/org/ballerinalang/net/websocket/WebSocketConnectorPortBindingListener.java
- websocket-native/src/main/java/org/ballerinalang/net/websocket/WebSocketConstants.java
- websocket-native/src/main/java/org/ballerinalang/net/websocket/serviceendpoint/Start.java
> Add a different port binding listener to WS module

- websocket-ballerina/websocket_errors.bal
> Fix build failure

- websocket-ballerina/Package.md
> Introduce sync client in package.md

- websocket-ballerina/tests/websocket_client_exceptions.bal
- websocket-ballerina/websocket_async_client.bal
- websocket-ballerina/websocket_sync_client.bal
> Rename WebsocketClientConfiguration to ClientConfiguration

- README.md
- websocket-ballerina/Package.md
> Update doc links

- .github/workflows/publish-release.yml
- gradle.properties
- websocket-ballerina/build.gradle
> Enable publishing to Ballerina central

- websocket-ballerina/service_endpoint.bal
- websocket-native/src/main/java/module-info.java
- websocket-native/src/main/java/org/ballerinalang/net/websocket/WebSocketConstants.java
- websocket-native/src/main/java/org/ballerinalang/net/websocket/serviceendpoint/InitEndpoint.java
Earlier this part was there in the HTTP module. Moved it to websocket module
> Create listener configuration in websocket module itself

- build.gradle
- websocket-ballerina/build.gradle
> Re-order Build Tasks to Publish to the Ballerina Central

- websocket-ballerina/build.gradle
> Throw exception when central token not present

- websocket-ballerina/build.gradle
> Avoid publishing to central for SNAPSHOT versions

- websocket-ballerina/tests/cookie_async_client_test.bal
- websocket-ballerina/tests/cookie_sync_client_test.bal
- websocket-ballerina/tests/websocket_client_failure.bal
- websocket-ballerina/websocket_async_client.bal
- websocket-ballerina/websocket_sync_client.bal
$subject.
Fix the issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/978
> Re-introduce cookie support for websocket clients

- .github/workflows/pull-request.yml
> Change branch from master to main

- .github/workflows/pull-request.yml
Add if clause to make codecov step trigger only for a pull_request
> Add If Clause for Codecov Action

- build.gradle
- gradle.properties
- websocket-ballerina/build.gradle
> Remove reflect transitive dependency

- build.gradle
- gradle.properties
> Remove encoding module dependencies

- websocket-ballerina/websocket_async_client.bal
- websocket-ballerina/websocket_failover_client.bal
- websocket-ballerina/websocket_sync_client.bal
> Comment out the retry and failover codes

- websocket-ballerina/tests/cookie_sync_client_test.bal
- websocket-ballerina/tests/simple_server_without_ping_resource.bal
- websocket-ballerina/tests/sync_client_ping_pong.bal
- websocket-ballerina/tests/websocket_ping_pong.bal
- websocket-ballerina/websocket_async_client.bal
- websocket-ballerina/websocket_sync_client.bal
> Move pingponghandler service to client configuration

- websocket-ballerina/build.gradle
> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763
> Add extracted bala in the zip artifact

- websocket-ballerina/service_endpoint.bal
- websocket-ballerina/websocket_async_client.bal
- websocket-ballerina/websocket_failover_client.bal
> Extend HTTP related record types

- websocket-ballerina/build.gradle
> Add -c flag to build command
> Related to ballerina-platform/ballerina-lang#29032
> Add -c flag to build command

- websocket-ballerina/websocket_caller.bal
- websocket-ballerina/websocket_connector.bal
- websocket-ballerina/websocket_sync_client.bal
- websocket-native/src/main/java/org/ballerinalang/net/websocket/actions/websocketconnector/Close.java
> Make the close function to accept a decimal value as the timeout

- websocket-ballerina/auth_types.bal
- websocket-ballerina/tests/sync_client_oauth2_test.bal
$subject
Related to https://github.com/ballerina-platform/module-ballerina-oauth2/pull/111
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/584
> Update for oauth2 refresh token grant config API

- websocket-ballerina/Package.md
> Remove async client BBE from package.md

- websocket-ballerina/tests/sync_client_idle_timeout.bal
- websocket-ballerina/tests/sync_client_onError.bal
- websocket-ballerina/tests/sync_client_ping_pong.bal
- websocket-ballerina/tests/sync_client_test_bytes.bal
- websocket-ballerina/tests/sync_client_test_text.bal
- websocket-ballerina/tests/sync_connection_close.bal
- websocket-ballerina/tests/websocket_custom_headers_test.bal
- websocket-ballerina/tests/websocket_simple_proxy_server.bal
> Migrate to new lang changes

- websocket-ballerina/tests/websocket_client_exceptions.bal
> Temporary disable a test

- .github/pull_request_template.md
- .github/workflows/build-master.yml
- .github/workflows/publish-release.yml
- changelog.md
- websocket-ballerina/build.gradle
$subject.
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/1198
> Add change log and update pull request yaml

- websocket-ballerina/tests/sync_client_read_binary_chunks_test.bal
- websocket-ballerina/tests/sync_client_send_text_data_chunk_test.bal
- websocket-ballerina/tests/sync_client_ssl_test.bal
- websocket-ballerina/tests/sync_client_test_text.bal
- websocket-ballerina/tests/test_caller_util_functions.bal
- websocket-ballerina/websocket_connector.bal
$subject.
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1245
No API changes. Adding a couple of test cases.
> Add test cases for caller/client util functions

- changelog.md
- websocket-ballerina/service_endpoint.bal
- websocket-ballerina/tests/malformed_url_test.bal
- websocket-native/src/main/java/org/ballerinalang/net/websocket/client/SyncInitEndpoint.java
Fix the issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/1142
> Return an error when an invalid URL is given

- build.gradle
- websocket-ballerina/build.gradle
> Strip stdlib dependency version

- README.md
> Fix the Readme file

- websocket-ballerina/build.gradle
Filter includes for code coverage
Improvement along with https://github.com/ballerina-platform/ballerina-lang/issues/30093
> Filter includes for code coverage

- changelog.md
- websocket-native/src/main/java/org/ballerinalang/net/websocket/WebSocketResourceDispatcher.java
Fix the issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/1313
> Fix the issue of dispatching to remote functions when observability is enabled

- websocket-ballerina/build.gradle
Set flag to enable Jacoco Coverage XML generation. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30381
> Set flag to enable Jacoco Coverage XML generation

- websocket-ballerina/auth_utils.bal
$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1375
> Improve the client authentication error message

- websocket-ballerina/build.gradle
> Make ballerina build depend of compiler plugin build

- websocket-ballerina/build.gradle
Update flag for coverage format from '--jacoco-xml' to '--coverage-format=xml'
> Update flag for coverage format

- websocket-ballerina/websocket_sync_client.bal
> Fix last accessed time in http:Cookies

- websocket-ballerina/service_endpoint.bal
> Make start function public

- websocket-ballerina/Module.md
> Fix Module.md in websocket package

- websocket-ballerina/tests/cookie_sync_client_test.bal
- websocket-ballerina/websocket_connector.bal
- websocket-ballerina/websocket_sync_client.bal
> Improve cookie test case and remove unwanted codes

- websocket-ballerina/Module.md
- websocket-ballerina/websocket_errors.bal
Fix docs in WebSocket package.
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1542
https://github.com/ballerina-platform/ballerina-standard-library/issues/1541
https://github.com/ballerina-platform/ballerina-standard-library/issues/1543
> Fix docs in WebSocket package

- .github/workflows/publish-release.yml
> Make publish to central false in the release action

- README.md
- ballerina/Package.md
$subject. 
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/1682
> Remove Ballerina google group references

- native/build.gradle
- native/src/main/java/module-info.java
> Remove unused ballerina-config dependency

- native/src/main/java/io/ballerina/stdlib/websocket/server/WebSocketServicesRegistry.java
> Change the log level of message

- ballerina/tests/websocket_custom_headers_test.bal
- native/src/main/java/io/ballerina/stdlib/websocket/WebSocketConstants.java
- native/src/main/java/io/ballerina/stdlib/websocket/WebSocketResourceDispatcher.java
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/916
> Add support for int,boolean,float parsing for path params

- .github/workflows/publish-release.yml
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/build.gradle
- build-config/resources/Ballerina.toml
- build-config/resources/CompilerPlugin.toml
- gradle.properties
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/1746
>  Make the Ballerina Project Tooling Friendly

- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/websocket/compiler/WebSocketServiceValidationTest.java
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_38/Ballerina.toml
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_38/service.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/websocket/plugin/WebSocketServiceValidatorTask.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/websocket/plugin/WebSocketUpgradeServiceValidatorTask.java
Fixes:https://github.com/ballerina-platform/ballerina-standard-library/issues/2054
> Skip plugin validations if the program has compilation errors

- load-tests/chat_application/deployment/ingress.yaml
- load-tests/chat_application/scripts/chat-app.jmx
> Change configs for load test

- examples/build.gradle
> Remove --with-tests

- ballerina/Ballerina.toml
- ballerina/tests/simple_server_without_ping_resource.bal
- ballerina/websocket_types.bal
- changelog.md
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_28/service.bal
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_29/service.bal
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_30/service.bal
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_31/service.bal
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_32/service.bal
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_33/service.bal
- gradle.properties
$subject related to https://github.com/ballerina-platform/ballerina-lang/issues/33834
Build will pass once the related lang change is completed
> Make service distinct

- gradle.properties
$subject related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2396
> Bump gradle plugin

- .github/workflows/publish-release.yml
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2426
> Add cleaning phase to the release action

- load-tests/chat_application/scripts/chat-app.jmx
> Increase the user count and test duration

- load-tests/chat_application/scripts/chat-app.jmx
> Reduce the user count to 1

- load-tests/chat_application/scripts/chat-app.jmx
> Increase the timeout to 900 seconds

- load-tests/chat_application/scripts/run.sh
> Pass Jusers param as it is used in final csv generation

- load-tests/chat_application/scripts/chat-app.jmx
> Increase the user count to 5

- native/src/main/java/io/ballerina/stdlib/websocket/WebSocketResourceDispatcher.java
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2383
> Migrate Java interop calls to latest ballerina runtime APIs

- load-tests/chat_application/scripts/chat-app.jmx
> Increase the user count to 10

- ballerina/tests/auth_declarative_basic_auth_test.bal
- ballerina/tests/auth_declarative_bearer_token_auth_test.bal
- ballerina/tests/auth_declarative_jwt_auth_test.bal
- ballerina/tests/test_upgrade_service_panic.bal
> Fix testerina compilation failures

- ballerina/service_endpoint.bal
- ballerina/tests/server_idle_timeout_test.bal
- ballerina/tests/start_attach_detach_stop_test.bal
- ballerina/websocket_types.bal
> Introduce UpgradeService service type

- ballerina/Ballerina.toml
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/websocket/compiler/WebSocketServiceValidationTest.java
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_39/Ballerina.toml
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_39/service.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/websocket/plugin/PluginConstants.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/websocket/plugin/WebSocketServiceValidator.java
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2491
> Do validation for onPing and onPong

- docs/readMessage-api.md
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2332
> Add a proposal for readMessage API

- .github/workflows/process-load-test-result.yml
- .github/workflows/trigger-load-tests.yml
> Automate PR merging of load tests

- load-tests/chat_application/scripts/pre_run.sh
$subject as there has been a performance cloud refactoring.
> Update the path of the Jmeter 

- load-tests/chat_application/scripts/pre_run.sh
> Fix permission denied issue when copying files

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- ballerina/tests/test_readonly_values.bal
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/websocket/compiler/WebSocketServiceValidationTest.java
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_40/Ballerina.toml
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_40/service.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/websocket/plugin/Utils.java
- native/src/main/java/io/ballerina/stdlib/websocket/WebSocketResourceDispatcher.java
$subject.
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2619
> Add support for intersection type

- docs/spec/spec.md
> Update the introduction section of the specification

- ballerina/annotation.bal
- ballerina/service_endpoint.bal
- ballerina/websocket_caller.bal
- ballerina/websocket_sync_client.bal
- ballerina/websocket_types.bal
> Fix API docs

- docs/spec/spec.md
> Add link to the GitHub issues

- README.md
> Change the url

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/auth_desugar.bal
- native/src/main/java/io/ballerina/stdlib/websocket/server/OnUpgradeResourceCallback.java
$subject related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2742
> Refactor the internal error handling of auth-desugar

- examples/build.gradle
> Fix Dependencies.toml path

- README.md
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/Module.md
- ballerina/Package.md
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2748
> Update doc titles to sentence case

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/websocket/compiler/WebSocketServiceValidationTest.java
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_41/Ballerina.toml
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_41/service2.bal
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_41/service3.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/websocket/plugin/WebSocketServiceValidator.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/websocket/plugin/WebSocketUpgradeServiceValidator.java
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2827 and https://github.com/ballerina-platform/ballerina-standard-library/issues/2825
> Fix compiler plugin crashes

- compiler-plugin/src/main/java/io/ballerina/stdlib/websocket/plugin/WebSocketUpgradeServiceValidator.java
> Avoid possible type casting error

- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/trivy-scan.yml
- native/build.gradle
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2902
> Update Trivy scan-type to enable JAR scanning

- ballerina/tests/http_query_param_binding_test.bal
- native/src/main/java/io/ballerina/stdlib/websocket/WebSocketResourceDispatcher.java
$subject.
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2903
> Change the status code from 404 to 400 for query param failures

- gradle.properties
> Update Netty version to the 4.1.77.Final

- gradle.properties
> Update Http version to the 2.2.2-20220517-143200-ae037ab

- gradle.properties
> Update the lang version to 2201.1.0-rc1.9

- build-config/resources/Ballerina.toml
- gradle.properties
> Update Ballerina Lang version

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/websocket/compiler/WebSocketServiceValidationTest.java
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_42/Ballerina.toml
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_42/service2.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/websocket/plugin/WebSocketUpgradeServiceValidator.java
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2916
- ~[ ] Updated the specification~
- ~[ ] Updated the changelog~
> Fix compiler plugin issue

- ballerina/Ballerina.toml
- build-config/resources/Ballerina.toml
- gradle.properties
> Upgrade the Ballerina distribution version to 2201.0.4

- ballerina/Ballerina.toml
> Update distribution version in toml

- compiler-plugin/src/main/java/io/ballerina/stdlib/websocket/plugin/WebSocketServiceValidator.java
> Fix the compilation failure

- examples/tic-tac-toe/server/server.bal
> Improve the Tic Tac Toe example 

- examples/tic-tac-toe/server/server.bal
This PR is to make possible variables final.
Also, I've mistakenly removed the assignment to the `next` variable. But we need to keep the global `next` variable updated as it is required to maintain the status if the user refreshes the page.
> Make possible variables final and fix a bug

- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_11/service.bal
The build has failed due to the changes done in this PR https://github.com/ballerina-platform/ballerina-lang/pull/36732
> Fix the compiler plugin test failure

- ballerina/auth_desugar.bal
> Fix warnings of the WebSocket module

- native/src/main/java/io/ballerina/stdlib/websocket/WebSocketUtil.java
- native/src/main/java/io/ballerina/stdlib/websocket/client/SyncInitEndpoint.java
- native/src/main/java/io/ballerina/stdlib/websocket/client/listener/RetryWebSocketClientHandshakeListener.java
- native/src/main/java/io/ballerina/stdlib/websocket/client/listener/SyncClientConnectorListener.java
- native/src/main/java/io/ballerina/stdlib/websocket/client/listener/WebSocketHandshakeListener.java
Fixes:https://github.com/ballerina-platform/ballerina-standard-library/issues/3172
> Fix intermittent test failure

- ballerina/Dependencies.toml
- ballerina/tests/invalid_base_path_test.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/websocket/server/WebSocketServerListener.java
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3296
> Fix the issue server sending 500 Internal server error when the client gives an incorrect base path in the url

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/tests/sync_client_idle_timeout.bal
- ballerina/tests/sync_client_onError.bal
- ballerina/tests/sync_client_ping_pong.bal
- ballerina/tests/sync_client_test_bytes.bal
- ballerina/tests/sync_client_test_text.bal
- ballerina/tests/sync_connection_close.bal
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3437
> Fix test failure after testerina migration

- ballerina/tests/sync_client_idle_timeout.bal
- ballerina/tests/sync_client_onError.bal
- ballerina/tests/sync_client_ping_pong.bal
- ballerina/tests/sync_client_test_bytes.bal
- ballerina/tests/sync_client_test_text.bal
- ballerina/tests/sync_connection_close.bal
- load-tests/chat_application/results/summary.csv
> Sync with master

- .github/workflows/build-with-bal-test-native.yml
- README.md
- examples/build.gradle
- gradle.properties
> $Subject
> Part of : [`Incorporate GraalVM native-image test build to Std Libs daily build #3316`](https://github.com/ballerina-platform/ballerina-standard-library/issues/3316)
N/A
> Add `Build with bal test native` workflow

- docs/spec/spec.md
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3794
> Update the WebSocket specification with data binding rules

- docs/spec/spec.md
> Fix issues in the spec

- ballerina/Ballerina.toml
- gradle.properties
> Update MIME and HTTP to released versions

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- ballerina/tests/test_data_binding_union.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/websocket/WebSocketUtil.java
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3909
> Fix data binding error when a union type is used

- .github/workflows/pull-request.yml
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/3988
> Add Codecov upload retry step for WebSocket module

- README.md
> Update last commit badge url in README

- docs/proposals/dispatching-to-custom-remote-functions.md
> Add the custom remote functions proposal to the proposals directory

- .github/workflows/process-load-test-result.yml
- .github/workflows/pull-request.yml
- .github/workflows/trigger-load-tests.yml
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/4098
> Add codecov token to pr build workflow and add workflow calls to load tests 

- ballerina/Dependencies.toml
- native/spotbugs-exclude.xml
- native/src/main/java/io/ballerina/stdlib/websocket/WebSocketResourceCallback.java
> Do a system exit when panicked from the service

- ballerina/Dependencies.toml
- ballerina/tests/test_dispatching_special_charachters.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/websocket/WebSocketResourceDispatcher.java
- native/src/main/java/io/ballerina/stdlib/websocket/serviceendpoint/Register.java
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4320
> Fix dispatching issue when the path has `-`

- load-tests/chat_application/scripts/pre_run.sh
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4342
> Update JMeterWebSocketSampler.jar download url

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/tests/custom_remote_functions.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/websocket/WebSocketResourceDispatcher.java
Fix the https://github.com/ballerina-platform/ballerina-standard-library/issues/4355
> Fix the issue of dispatching to custom remote functions if `onMessage` function is present 

- examples/chat-application/README.md
- examples/taxi-service-management/README.md
- examples/tic-tac-toe/README.md
> Update meta info of examples

- .github/workflows/build-with-bal-test-native.yml
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/4142
> Add graalvm check for pull requests

- ballerina/Dependencies.toml
- ballerina/tests/custom_remote_functions.bal
- ballerina/tests/on_binary_with_on_error.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/websocket/WebSocketResourceDispatcher.java
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4403
> Dispatch `onError` when there is a data binding error

- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/websocket/compiler/WebSocketServiceValidationTest.java
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_40/service.bal
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_58/Ballerina.toml
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_58/server.bal
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_58/server2.bal
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_58/server3.bal
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_58/server4.bal
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_59/Ballerina.toml
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_59/server.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/websocket/plugin/PluginConstants.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/websocket/plugin/Utils.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/websocket/plugin/WebSocketServiceValidator.java
Fix the issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/4387
and 
https://github.com/ballerina-platform/ballerina-standard-library/issues/4294
> Add validation for contradicting return types

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- changelog.md
- gradle.properties
> Update changelog after 2.7.1 release

- .github/workflows/build-with-bal-test-graalvm.yml
- README.md
- examples/build.gradle
- gradle.properties
> $Subject
Part of : https://github.com/ballerina-platform/ballerina-standard-library/issues/4548
N/A
> Incoperate native build command change

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- gradle.properties
> Update dependency version

- .github/workflows/build-timestamped-master.yml
- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trivy-scan.yml
- .github/workflows/update_spec.yml
- README.md
- ballerina/Ballerina.toml
- build-config/checkstyle/build.gradle
- build-config/resources/Ballerina.toml
- build.gradle
- compiler-plugin/build.gradle
- compiler-plugin/spotbugs-exclude.xml
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- native/spotbugs-exclude.xml
- native/src/main/java/io/ballerina/stdlib/websocket/WebSocketUtil.java
- native/src/main/java/io/ballerina/stdlib/websocket/observability/WebSocketObservabilityConstants.java
- settings.gradle
> Migrate to Java 17

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
> Update netty version

- examples/chat-application/A Basic Chat Application using the Ballerina WebSocket Module.md
- examples/taxi-service-management/Building a Real-Time Taxi Management Service with Ballerina.md
- examples/tic-tac-toe/Building a Real-Time Multiplayer Tic Tac Toe Game using Ballerina.md
This is for SEO purposes so the examples get listed on search engines.
> Update README files of examples

- changelog.md
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/websocket/compiler/WebSocketServiceValidationTest.java
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_59/server.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/websocket/plugin/Utils.java
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4518
> Fix Compilation Error for Stream Type With "Error" Substring in Signature

- docs/spec/spec.md
This temporarily fixes the rendering issue in the website
related issue: https://github.com/ballerina-platform/ballerina-dev-website/issues/7884
> Remove nested example code blocks from the spec

- examples/chat-application/server/tests/test_chat_server.bal
> Remove unwanted log

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
Part of: https://github.com/ballerina-platform/ballerina-standard-library/issues/4908
> Upgrade Netty version

- ballerina/Ballerina.toml
- gradle.properties
> Remove http timestamp version

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- changelog.md
- gradle.properties
Part of : https://github.com/ballerina-platform/ballerina-standard-library/issues/4908
> [2201.6.x] Update Netty version

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- changelog.md
- gradle.properties
Part of: https://github.com/ballerina-platform/ballerina-standard-library/issues/4908
> [2201.4.x] Update the netty version

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- changelog.md
- gradle.properties
Part of: https://github.com/ballerina-platform/ballerina-standard-library/issues/4908
> [2201.3.x] Update netty version

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
> Update to Snapshot version

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/4908
> [2201.2.x] Update the Netty version

- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
> Temporary disable the trivy scan

- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
Reverts ballerina-platform/module-ballerina-websocket#1165
> Revert "Temporary disable the trivy scan"

- README.md
To improve the quality of the `README.md` content
> Improve `README.md` text with concise, yet clear messages.

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
Part of https://github.com/ballerina-platform/ballerina-library/issues/6249
> [master] Update the Netty version

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- gradle.properties
Part of https://github.com/ballerina-platform/ballerina-library/issues/6249
> [2201.8.x] Update the netty version

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- gradle.properties
> [2201.7.x] Update the netty version

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- gradle.properties
> Update the HTTP version

- .github/workflows/build-timestamped-master.yml
- .github/workflows/build-with-bal-test-graalvm.yml
- .github/workflows/central-publish.yml
- .github/workflows/process-load-test-result.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trigger-load-tests.yml
- .github/workflows/trivy-scan.yml
> Update the work flows

- ballerina/Dependencies.toml
- ballerina/annotation.bal
- changelog.md
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/websocket/compiler/WebSocketServiceValidationTest.java
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_60/Ballerina.toml
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_60/server.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/websocket/plugin/PluginConstants.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/websocket/plugin/WebSocketUpgradeServiceValidatorTask.java
- docs/spec/spec.md
Related issue: https://github.com/ballerina-platform/ballerina-library/issues/6757
> Introduce `dispatcherStreamId` service config

- .github/workflows/build-with-bal-test-graalvm.yml
Part of: https://github.com/ballerina-platform/ballerina-library/issues/3755
N/A
> Enable GraalVM check for windows

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/tests/test_data_binding_json.bal
- ballerina/tests/test_data_binding_xml.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/websocket/WebSocketResourceCallback.java
> $subject
Resolves [JSON Parsing Error in WebSocket Client](https://github.com/ballerina-platform/ballerina-library/issues/7720)
> Fix JSON response parsing issue with escaped double quotes in WebSocket service

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
- native/src/main/java/io/ballerina/stdlib/websocket/WebSocketConstants.java
- native/src/main/java/io/ballerina/stdlib/websocket/WebSocketResourceDispatcher.java
- native/src/main/java/io/ballerina/stdlib/websocket/serviceendpoint/Register.java
> $Subject
Related HTTP change - https://github.com/ballerina-platform/module-ballerina-http/pull/2427
N/A
> Fix regression issues due to url encoding fix in http

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
Part of: https://github.com/ballerina-platform/ballerina-library/issues/8174
> **Note**: This package is not affected by the above vulnerability. But upgrading for consistency and to verify that the package does not break with the fixed version
> [2201.12.x] Update Netty Version

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
> Update http version

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- changelog.md
- gradle.properties
> $Subject
Part of: https://github.com/ballerina-platform/ballerina-library/issues/8214
N/A
> Address `CVE-2025-58056` and `CVE-2025-58057` security vulnerabilities

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
> Prepare for Update 13 release
